### ISSUE TITLE
ImageOrView abstraction

### ISSUE THREAD

**Issue by masonium** [msiglreith/grr#14]
There are some places (`bind_image_views`, `bind_storage_image_views`) where `grr::Device` requires an `ImageView`, even though OpenGL is just taking a texture underneath. I assume this is because Vulkan requires these operations to operate on image views, but it does seem like extra work for the user. Would you be open to something like an `ImageOrView` enum that trivially implements `From<Image>` and `From<ImageView>`, so functions could take an `Img: Into<ImageOrView>` wherever it makes sense?

Alternatively, if you prefer the interface to strictly take views, how would you feel about a `create_image_and_view` sub-function, that returns a both the image and a trivial view of the entire image? The inputs to `create_image` are sufficient, I believe.

**Comment by msiglreith** [comment]
Right, OpenGL only has a concept of textures which underneath share the image storage when creating a view. The easiest way would be to add an `as_view` function which just returns the view with the same handle as the image. The only caveat here is that the `ImageViewType` might now be straightforward as for example 2D Arrays and Cubemaps may have the same `ImageType` on creation. (See target selection logic https://github.com/msiglreith/grr/blob/master/src/image.rs#L196)
But I think these can be actually made more clear by always creating a texture array, cubemaps would then always require a view

**Comment by masonium** [comment]
Re-using the internal handle (so that you have an `Image` and `ImageView` that share a handle) will give you problems if you say, delete one of them. Specifically, deleting the `ImageView` would also delete the `Image` it references. That's why I suggested the `create_image_and_view`, so you don't need to repeat all of the information you give to `create_image` that you would need for a fresh view object.

Otherwise, I like the idea of arrays being the default for images, and cubes requiring a view. That would be clearer from an interface perspective, and that target selection logic would be a bit simpler.

(Sidenote: I'm not actually sure what happens if you delete a texture that has a view associated with it. I assume that the underlying storage is effectively reference counted, so the view is still valid, but that's just a guess).

**Comment by msiglreith** [comment]
Created a PR based on the `create_image_and_view` approach - there is indeed an drawback with `as_view` due to deletion of view which would also delete the image.

> (Sidenote: I'm not actually sure what happens if you delete a texture that has a view associated with it. I assume that the underlying storage is effectively reference counted, so the view is still valid, but that's just a guess).

Yes, it's internally reference counted, I would still suggest to treat image as the object owning the memory and views as weak references
