### ISSUE TITLE
Relicense to Apache & MIT

### ISSUE THREAD

**Issue by msiglreith** [msiglreith/grr#3]
As the library as already close to feature complete with regards to GL 4.5 core spec, I want to move towards the 'standard' licensing approch in the rust ecosystem. MPL was to hope people contribute some issues if they stumble upon it but didn't work out (which is totally fine!)

**Comment by Bzomak** [comment]
Cargo.toml still shows the license as MPL-2.0.
Similarly, the majority of the source code files still have MPL-2.0 headers.
