### ISSUE TITLE
No Cerberus_LP.fbx when running example pbr

### ISSUE THREAD

**Issue by noctice007** [msiglreith/grr#31]
The error message
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Unable to open file "**grr-master/examples/pbr/assets/Cerberus_LP.fbx\"."**', **examples/pbr/pbr.rs:84:14**
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by msiglreith** [comment]
Hi!
I didn't include the assets in the repository as mentioned in the [README](https://github.com/msiglreith/grr#maybe-physically-based-rendering-ibl).
You can find the model and env map in the following links:
- http://artisaverb.info/PBT.html (bottom of the page)
- http://www.hdrlabs.com/sibl/archive.html (popcorn lobby)
